name: crypto-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  # Core packages for data processing
  - python=3.10
  - pandas=2.1.1
  - numpy=1.26.0
  
  # Data visualization
  - matplotlib=3.8.0
  - seaborn=0.13.0
  
  # Jupyter notebook support
  - jupyter=1.0.0
  - ipython=8.15.0
  - notebook=7.0.4
  
  # Date/time handling
  - python-dateutil=2.8.2
  
  # AWS S3 upload support
  - boto3=1.33.0
  - botocore=1.33.0
  
  # Additional tools
  - pip=23.2.1
  - pip:
    - nbformat>=5.7.0