name: crypto-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - boto3
  - botocore
  - pip
  - pip:
    - snowflake-snowpark-python